---
version: "2.1"
services:
### SONARR
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC+03:00
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/configs/sonarr:/config
      - /mnt/4CA6BC377086A62B/MEDIA/emby/tvshows:/tv #optional
      - /mnt/4CA6BC377086A62B/MEDIA/emby/downloads:/downloads #optional
    networks:
      mediacenter:
        ipv4_address: 172.19.0.5
    ports:
      - 8989:8989
    restart: unless-stopped
### RADARR    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC+03:00
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/configs/radarr:/config
      - /mnt/4CA6BC377086A62B/MEDIA/emby/movies:/movies #optional
      - /mnt/4CA6BC377086A62B/MEDIA/emby/downloads:/downloads #optional
    networks:
      mediacenter:
        ipv4_address: 172.19.0.6
    ports:
      - 7878:7878
    restart: unless-stopped
### PROWLARR    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC+03:00
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/configs/prowlarr:/config
    networks:
      mediacenter:
        ipv4_address: 172.19.0.4
    ports:
      - 9696:9696
    restart: unless-stopped
### LIDARR    
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC+03:00
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/configs/lidarr/config:/config
      - /mnt/4CA6BC377086A62B/MEDIA/emby/music:/music #optional
      - /mnt/4CA6BC377086A62B/MEDIA/emby/downloads:/downloads #optional
    networks:
      mediacenter:
        ipv4_address: 172.19.0.3
    ports:
      - 8686:8686
    restart: unless-stopped
### BAZARR    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC+03:00
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/configs/bazaar:/config
      - /mnt/4CA6BC377086A62B/MEDIA/emby/movies:/movies #optional
      - /mnt/4CA6BC377086A62B/MEDIA/emby/tvshows:/tv #optional
    networks:
      mediacenter:
        ipv4_address: 172.19.0.7
    ports:
      - 6767:6767
    restart: unless-stopped
### QBITTORRENT
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/configs/qbittorrent:/config
      - /mnt/4CA6BC377086A62B/MEDIA/emby/downloads:/downloads
    networks:
      mediacenter:
        ipv4_address: 172.19.0.2
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
networks:
  mediacenter:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/16
