---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/sonarr/data:/config
      - /mnt/4CA6BC377086A62B/MEDIA/sonarr/tvseries:/tv #optional
      - /mnt/4CA6BC377086A62B/MEDIA/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/radarr/data:/config
      - /mnt/4CA6BC377086A62B/MEDIA/radarr/movies:/movies #optional
      - /mnt/4CA6BC377086A62B/MEDIA/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/lidarr/appdata/config:/config
      - /mnt/4CA6BC377086A62B/MEDIA/lidarr/music:/music #optional
      - /mnt/4CA6BC377086A62B/MEDIA/lidarr/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/bazarr/config:/config
      - /mnt/4CA6BC377086A62B/MEDIA/bazarr/movies:/movies #optional
      - /mnt/4CA6BC377086A62B/MEDIA/bazarr/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/4CA6BC377086A62B/MEDIA/emby/library:/config
      - /mnt/4CA6BC377086A62B/MEDIA/emby/tvshows:/data/tvshows
      - /mnt/4CA6BC377086A62B/MEDIA/emby/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
